version: "3.8"
services:
  graphql:
    container_name: server
    image: server
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 4000:4000
