version: "3.8"
services:
  app:
    container_name: web-client
    image: web-client
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000